export const OPTIONS_FETCH = 'OPTIONS_FETCH';
export const STATUSES_FETCH = 'STATUSES_FETCH';
export const HIERARCHY_FETCH_START = 'HIERARCHY_FETCH_START';
export const HIERARCHY_FETCH_DONE = 'HIERARCHY_FETCH_DONE';
export const HIERARCHY_FETCH_ERROR = 'HIERARCHY_FETCH_ERROR';
export const HIERARCHY_SAVE_START = 'HIERARCHY_SAVE_START';
export const HIERARCHY_SAVE_DONE = 'HIERARCHY_SAVE_DONE';
export const HIERARCHY_SAVE_ERROR = 'HIERARCHY_SAVE_ERROR';
